- README.md
The Selectize link was 404ed. Added correct link: https://selectize.github.io/selectize.js/
> Corrected broken Selectize link in README.md

- src/validator.js
In the README.md file, the `required_by_default` option is described as:
> If `true`, all schemas that don't explicitly set the `required` property will be required.
But schemas that explicitly set the `required` property do not overwrite the `required_by_default` option as advertised, so they are always required (even with `required = false` using JSON Schema 3 syntax or `required = []` using JSON Schema 4 syntax).
The issue can be demonstrated with this code snippet which does not pass validation:
```
var element = document.querySelector("#editor");
var options = {
"required_by_default": true,
"schema": {
"type": "object",
"properties": {
"a": {"type": "string"},
"b": {"type": "string"}
},
"required": ["a"]  // should overwrite `required_by_default` but does not
}
};
var editor = new …
```
> Allow required to overwrite required_by_default

- src/core.js
json-editor doesn't give the registered event handlers context for what editor instance changed.
Usually this isn't a problem if a reference to the json-editor instance is preserved, e.g.
```
var editor = new JSONEditor(container, {});
jQuery(container).data('editor', editor);
editor.on('change',function() {
var value = jQuery(container).data('editor').getValue();
});
```
But in the above case if json-editor rendered text input element receives a change and container element is removed from DOM without the text input losing focus, then json-editor does call trigger('change') and jQuery(container).data('editor') is undefined.
With the proposed change it's possible to do `this.getValue()` in the event handler without issues.
> Call event handlers with context

- src/core.js
- tests/codeceptjs/editors/validation_test.js
- tests/pages/validation.html
* added support for relative file paths
* added validation.html to test suite (implicitly tests relative file paths)
In an ideal world the tests in validation.html would be converted to tests native to the test-suite, but recreating the 129 validation-tests isn't a trivial task. I made sure the successes were shown as well and created a codecept test for it.
The reason for testing with validation.html was that I had issues with relative file paths with external references and validations.html by accident referenced a schema with a relative external reference. Which was silently failing before in the browser's console, but was fixed with this change.
> relative filepaths + extended testsuite

- src/themes/bootstrap4.js
Change row column wrapper from <ul> to <div> in the column main wrapper for better comply with Bootstrap 4 grid columns spec, and address design alignment  issues.
> Better comply with Bootstrap 4 grid columns spec

- src/iconlib.js
Fix for some iconlib options where adding multiple classes as a string separated by spaces breaks the native `DOMTokenList` add api eg. `'foo bar'`
> Fix adding classes to DOMTokenList

- docs/signature.html
Fixed link to JSON-Editor in Signature editor example
> Fix of js link in signature editor example

- src/theme.js
Profiling showed that for large object trees, a significant portion of time was being spent in setButtonText.
Removing the `innerHTML += ' '` fixes this.
I also use a better-performing strategy for removing the contents of the button, although that's probably a premature optimization.
This is one small change that can impact #252 . Unfortunately, in the grand scheme of things, this still makes a barely-noticeable difference in the time it takes to set values in the editor. I think other changes are likely to be far more meaningful.
> Improve performance of theme.setButtonText

- README.md
- docs/cleave.html
- src/editors/string.js
Adds simple support for [cleave.js](https://nosir.github.io/cleave.js/) a library that Format your &lt;input/&gt; content when you are typing. See #247 
Works only with string types.
> Adds support for Cleave.js

- src/editor.js
- src/editors/number.js
- src/editors/select.js
- src/editors/string.js
I created a global "setInputAttributes" function in editor.js as it's pretty much the same code used in all editors except for the protected keys (which is a parameter for the new function)
Also added the functionality to select and number/integer types.
> Moved inputAttributes function to editor.js + support for number and select

- README.md
- docs/advanced.html
- docs/basic.html
- docs/cleave.html
- docs/css_integration.html
- docs/datetime.html
- docs/demo.html
- docs/index.html
- docs/materialize_css.html
- docs/multiple_upload_base64.html
- docs/recursive.html
- docs/select2.html
- docs/selectize.html
- docs/signature.html
- docs/starrating.html
- docs/upload.html
- docs/wysiwyg.html
Changed all occurrences of: 
https://cdn.jsdelivr.net/npm/@json-editor/json-editor/dist/
In docs/ and readme.me to:
https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/
Fixes the CDN problem outlined in #179
> Updated CDN links

- src/editor.js
Webpack (with Terser minifier) build fail because "protected" is reserved word and can not be used as variable name.
> Rename function variable named "protected"

- src/iconlibs/materialicons.js
`upload` icon was missing, thus exception was thrown at [materialize.js#L47](https://github.com/json-editor/json-editor/blob/e695bddebe80cae79cb622d41d89b50d9814ccef/src/themes/materialize.js#L47)
```js
if (text) {
icon.classList.add('left');
icon.style.marginRight = '5px';
}
```
as `icon` war for `upload` was undefined.
> Material Icons | Adding missed uploads icon

- README.md
- src/editors/string.js
Accept `schema.options.ace` as Ace Editor options per its instance.
Enable auto completion extension for example.
```json
"query": {
"type": "string",
"format": "sql",
"options": {
"ace": {
"enableBasicAutocompletion": true,
"enableLiveAutocompletion": true,
"enableSnippets": true						
}
}
}
```
> Accept schema.options.ace as Ace Editor options.

- README.md
- src/theme.js
- src/themes/bootstrap2.js
- src/themes/bootstrap3.js
- src/themes/bootstrap4.js
- src/themes/foundation.js
- src/themes/jqueryui.js
- src/themes/materialize.js
If [DOMPurify](https://github.com/cure53/DOMPurify) library is loaded, themes can render description as HTML text. Otherwise description is rendered as plain text.
> DOMPurify support for description text #329

- src/templates/underscore.js
The underscore library made a breaking change with version 1.7.  `_.template()` now returns a function.
https://underscorejs.org/#template
> Support underscore 1.7 and newer

- README.md
Added info about the missing option keyword `dependencies`.
Example of this feature: https://is.gd/YArsbq
> Added missing dependencies info

- src/editors/string.js
Defaults to "0" if no default value is set. Then value matches initial slider position.
Example Schema
````json
{
"type": "object",
"required": ["grade"],
"properties": {
"grade": {
"type": "integer",
"format": "range",
"maximum": 10,
"minimum": -10
}
},
"title": "Student"
}
````
> Fix of #326

- src/defaults.js
- src/editors/array/selectize.js
- tests/codeceptjs/editors/array_test.js
- tests/pages/array-selectize.html
Selectized array had not support of enums, also while running `setValue` it clears all known selectized options.
So, refreshing value is now looks like the following:
1) remove all options
2) append enum options, if present
3) append previously selected options
3rd step is here, as `arraySelectize` by default allowes the user to create new values, so this data has not to be lost.
`defaults.js` is altered also, because if `JSONEditor.plugins.selectize.enable` is set to `true` then it is expected to be everywhere and not to fall back into standard browser select.
> #222 added enum support for selectize arrays, tests

- README.md
- src/editor.js
- src/editors/array.js
- src/theme.js
- src/themes/bootstrap2.js
- src/themes/bootstrap3.js
- src/themes/bootstrap4.js
- src/themes/foundation.js
- src/themes/jqueryui.js
- src/themes/materialize.js
Allow HTML tags in headers if DOMPurify is loaded. (Just like my previous PR with HTML in descriptions)
Also If DOMPurify is not loaded, HTML tags will be filtered from header before display.
Test example. https://is.gd/w6RF5K
BTW: With all the recent bugfixes and new features, I think its time to make a new release?
> Allow HTML in header if DOMPurify is loaded

- src/editor.js
- src/editors/array.js
- src/editors/object.js
- Add support for `compact` in `src/objects.js` to hide title.
- Adds missing buttons to enable/disable state (src/array.js)
- Fixed problems with `dependencies` option not working with Boolean format (src/editor.js).  Test Case: https://is.gd/WzAiQq
- Fixes problem with JSON and collapse buttons setting `display: none;` on button and not container (properties button was only one that did it correctly. (src/object.js)
So now  `compact` in combination with hiding the buttons, will remove the "empty gap" in the layout.
> Fix of #382

- CHANGELOG.md
- src/editor.js
Fix of #231 - Allow use of dots "." in fieldnames.
Test Case: https://is.gd/P5sGXD
Before patch, label is "ackTimeout" (wrong)
After patch, label is "-Dsun.rmi.dgc.ackTimeout" (correct)
> Fix of #231 - Allow use of dots in fieldnames

- CHANGELOG.md
- src/editors/checkbox.js
Fixed #392 - Now setting checkbox value programmatically will trigger onchange correctly. (src/editors/checkbox.js)
> Fix of #392 - Checkbox failed to call onchange correctly 

- CHANGELOG.md
- README.md
- src/editors/select.js
- src/editors/selectize.js
Since Select2/Selectize are enabled globally, it's currently not possible to turn it of for a single property.  See #380 
This PR adds 2 new config options: "noselect2" and "noselectize" which can be used to disable select2/selectize on a specific property/field.
> disable select2/selectize for single property

- src/editors/datetime.js
Datetime fields of integer type fail to update the internal state (``this.value``) when ``setValue`` is called.
Steps to reproduce:
Create editor with schema: ``{"type": "integer",  "format": "datetime-local"}``
``editor.setValue(1562320800)``
``editor.getValue()`` will be ``undefined``
> Fix datetime integer setValue fails to update internal state

- src/validator.js
**Non-BC**
Adds new option parameter for overriding the error message generated when using patterns.
The normal errors when using patterns looks something like this (Which isn't very informative for non-programmers):
``
Value must match the pattern ^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$.
``
With this PR, you can set `options.patternmessage` to an alternate text which will then be displayed instead.
> Allow setting custom validation message for patterns

- src/core.js
- tests/README.md
- tests/codeceptjs/editors/inheritance_test.js
- tests/pages/inheritance.html
Fixes #422.
The changes required were fortunately fairly simple.
I've added a stub e2e test which simply checks all `required` fields in a two-layer hierarchy are added.
I scratched my head for about an hour wondering why four other e2e tests were failing and eventually worked out they were failing in the main repo too, but were being ignored by Travis because of the `@optional` tag. So I added some text to `./testing/README.md` to point this out to future contributors.
> Allow more than one layer of allOf inheritance

- src/editors/array/choices.js
- src/editors/array/selectize.js
- src/editors/base64.js
- src/editors/checkbox.js
- src/editors/choices.js
- src/editors/enum.js
- src/editors/multiple.js
- src/editors/multiselect.js
- src/editors/radio.js
- src/editors/select.js
- src/editors/selectize.js
- src/editors/signature.js
- src/editors/starrating.js
- src/editors/string.js
- src/editors/upload.js
- src/theme.js
- src/themes/bootstrap2.js
- src/themes/foundation.js
- src/themes/html.js
- src/themes/jqueryui.js
- src/themes/jsoneditor.barebones-theme.js
**Non-BC**
Passes the value of` isRequired()` to Theme label function so you can style the label differently if field is required. See #432 
Set's the classname "**required**" on the label element if field is required. So you can do something like this in CSS,
````css
/* adds a red star in front of label name */
label.required:before {
content: "* ";
color: red;
}
````
> Pass isRequired() value to Theme label functions

- src/editors/radio.js
- src/theme.js
- src/themes/bootstrap2.js
- src/themes/bootstrap3.js
- src/themes/bootstrap4.js
- src/themes/foundation.js
- src/themes/materialize.js
- src/themes/tailwind.js
**Refactored radio editor** (Fixes issues described in #420)
* Now extends `select` editor instead of `string` editor, which handles all `enum` variants.
* Added support for `inputAttributes` option.
* Moved rendering of elements from editor (hardcoded) to theme functions.
* Updated `checkbox` and `radio` rendering in all themes.
> Radiorefactor

- src/editors/array/choices.js
- src/editors/choices.js
- src/editors/datetime.js
- When the type of a field is not a string type (i.e. integer) changing the value or adding/removing array elements converts the internal value to string. This change will sanitize the internal state to the type defined by the schema.
- Array values can now be differently titled.
- Some code cleanup and simplification. When implementing support for Choices I just copied the Selectize implementation and went on from there getting it into a working state. I didn't take the time then to properly go through the code.
- Fixes #402 (was reproducible by me )
> Sanitize value of choices editors and cleanup

- src/editors/object.js
Prevent memory leak caused by attaching an anonymous listener to the document in object.js. Fixes #460 
Submitted this same PR an hour ago, realized a missed a line, then mucked up the commit trying to fix that mistake, so resubmitting.
| Breaks BC?    | ✔️
| Fixed issues  | #460
> Prevent memory leak

- src/editors/radio.js
- src/editors/string.js
- src/themes/materialize.js
| Breaks BC?    | ✔️ Good for 2.x
| Tests pass?   | Not run, shouldn't impact
| Fixed issues  | #205 
This is a partial fix for radio and range elements only. Tried to fix as generic as possible, added data-container-for attribute for element types wrapped in additional div, so that we know what's actually inside. This might be useful not only for Materialize theme in case some manipulation is needed in getFormControl() function.
> Fix overlapping label for radio and range Materialize theme (fixes #205)

- src/iconlibs/bootstrap2.js
- src/iconlibs/bootstrap3.js
- src/iconlibs/fontawesome3.js
- src/iconlibs/fontawesome5.js
- src/iconlibs/foundation2.js
- src/iconlibs/foundation3.js
Iconsets without the "copy" property threw an error in some themes.
> Added missing 'copy' icon. So errors are not thrown

- tests/pages/array-selectize.html
- tests/pages/string-ace-editor.html
- tests/pages/string-custom-attributes.html
- tests/pages/string-sceditor.html
I have removed obsolete plugin reference from tests and updated them to use new options method.
| Fixed issues  | #491
> Tests - Removed obsolete plugin reference and updated to use new options method

- config/webpack.prod.js
- src/core.js
- tests/unit/core.spec.js
| Tests pass?   | ✔️/❌ - somehow 
| Fixed issues  | #519 (partially, see below)
The original grunt build produced a single file that could be directly included in html files (by assigning JSONEditor to the window object) or imported into another javascript file using amd.
I don't see any way to achieve this with Webpack - instead it looks like you need to create different builds for the different target formats.
I have followed [this blogpost](https://tech.trivago.com/2015/12/17/export-multiple-javascript-module-formats/) to create a jsoneditor.amd.js build in adition to the other standard ones. However this …
> Created separate production builds for amd and var

- src/editors/select.js
| Fixed issues  | #516
Boolean values was typecast wrong when value was "undefined" or undefined (Happens when property is NOT required). Now lets the undefined value pass through. (The property value is not set if value is undefined)
> Fix of #516 

- tests/codeceptjs/editors/array_any_of_test.js
- tests/pages/array-anyof.html
test case for page `array-anyof.html` 
| Tests pass?   | ❌
| Fixed issues  | Test case for #459 
It doesn't work correctly, i don't know why.
```
I.clearField('root[items][0][id]');
I.click('.get-value');
I.seeInField('root[items][0][id]', '');
// todo: why this passed?
let r = I.see('Value must match the pattern ^[a-zA-Z0-9_]+$.');
assert.equal(r, true, 'it should appear');
```
It should be failed(when i operate on browser manually it didn't display a warning).
Please help.
> test case for page `array-anyof.html`

- docs/describedby.html
- src/core.js
- src/editors/describedby.js
- src/utilities.js
- src/validator.js
1. the local refs for `describedby` editor may wook poorly if i change `window.location.hash` ( which is common for single page application) or `window.locaiton.query` after editor instance is created. 
2. the `$extend` function didn't copy a array appropriately(deeply), which leads to a problem for recursively use of `describedby` editor. for example the shema likes:
``` json
缩进量：  引号 显示控制 
格式化JSON：
{
"title": "Property for Sale", 
"$ref": "#/definitions/single", 
"definitions": {
"multiple": {
"type": "array", 
"items": {
"$ref": "#/definitions/single"
}
}, …
```
> bugfix for local refs url support for SPA and recursively use the describedby editor

- README_ADDON.md
- src/editors/simplemde.js
In Chrome SimpleMDE content is not visible until focus is applied. This happens when the SimpleMDE editor is hidden. (Like when placed inside Tabs)
This fix adds a custom option "autorefresh" (NO CAMELCASE) based on the code from https://codemirror.net/doc/manual.html#addon_autorefresh
| Fixed issues  | #574
| Updated README/docs?   | ❌ 
Info about the "autorefresh" option have been added to `README_ADDON.md`
> Fix problem with content not being visible before focus

- src/validator.js
Fix of #580 - DescribedBy Editor doesn't validate referenced properties (they are always valid)
| Tests pass?   | ✔️#580
> Fix of #580 - DescribedBy Editor doesn't validate referenced properties (they are always valid)

- src/editors/object.js
| Is bugfix?    |❌
The property list in object editor can be filterable，for example, 
1. the origin property list looks like ![origin](http://chuantu.xyz/t6/702/1572427470x3703728804.png)
2. when I input some letters the property list become ![origin](http://chuantu.xyz/t6/702/1572427616x3661913030.png)
This feature may make it fast and convenience to locate a property if the editor has a large amount of available properties.
> filterable property list of object editor

- README.md
- docs/enumsource.html
- src/editors/select.js
#187 ported to 2.x version. 
@schmunk42 I noticed an odd behavior when using the provided example. When the new option `enum_source_value_auto_select` is NOT ENABLED (Default behavior) and you move an item from `possibleFonts` up/down, you get duplicate entries in `selectedFonts`
So should we enable the new option by default?
> enumSource reorder fix, preserve value at Move Up or Down for 2.x

- config/webpack.prod.js
- package.json
importing JSONEditor was not possible anymore.
With commonjs2 build target it is possible to import it using named import:
import { JSONEditor } from '@json-editor/json-editor'
> Add importable module as build target

- src/editors/object.js
- in editor.js the isRequired() function of the object.js was used,
this caused the #637 BUG
| Breaks backward-compatibility?    | ?
| Fixed issues  | #637 fixed by the PR
> rename isRequired to isRequiredObject - fix #637

- CHANGELOG.md
- src/core.js
- tests/codeceptjs/editors/object_test.js
- tests/pages/grid-strict.html
- tests/pages/grid.html
- tests/pages/object-required-properties.html
- Removed (commented out) Bootstrap 2/3, Foundation and Materialize Themes.
- Removed (commented out) Bootstrap 2/3, Foundation and Materialize Iconsets.
Files have **NOT** been removed from `src/`, so it's possible to include them again if needed.
| Fixed issues  | #643 
**Size differences:**
unminified: 516kb vs **460kb**
minified: 253kb vs **226kb**
Not sure if we should merge this yet. Was just created to see how much smaller the lib would be without them.
> Un-updated Themes and Iconlibs removed (commented out)

- package-lock.json
- package.json
- src/core.js
- src/schemaloader.js
- tests/unit/schemaloader.spec.js
| Breaks backward-compatibility?    | ✔️ some private method moved from core.js
core.js contains codes that configure the entire editor and codes that loads the schema to editor.
The code that loads the schema is less dependent on other modules, so separate it into another module.
> Split core.js. Add schemaloader.js module.

- src/themes/bootstrap4.js
Fixes #681 (Bootstrap4: When using category tabs, content of first tab is empty)
Also affects portion of #594
| Fixed issues  | #681
Test result:
```
Chrome 80.0.3987 (Linux 0.0.0): Executed 156 of 156 SUCCESS (4.832 secs / 3.834 secs)
TOTAL: 156 SUCCESS
```
Test machine:
```
$ uname -a 
Linux xxxxxxxx 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
> Override getFirstTab() from themes.js to fix #681

- src/editors/checkbox.js
- src/editors/multiselect.js
Added `id`/`for` attributes for `label`/`input[type=checkbox]` combinations (single checkbox and multiselect with checkbox style), so the label becomes clickable incase the theme doesn't nest the cechbox under the label (which is the case the Bootstrap 4 theme).
I used the `name` attribute, which I think should be globally unique? 
| Updated README/docs?   | -
> fix: checkbox/label should have unqiue id/for attribues for clickable label

- .gitignore
- CHANGELOG.md
- src/validator.js
| Fixed issues  | #716, #237 
This fixes only the validation messages appearing incorrectly for allOf because it isn't supported currently, just as oneOf and anyOf.
> Add allOf to existing validation ignore and add .vs into gitignore

- CHANGELOG.md
- src/editors/checkbox.js
- tests/codeceptjs/editors/checkbox_test.js
- tests/pages/checkbox-labels.html
| Fixed issues  | #714
This PR fixes #714 by testing [the same logic used by `object.js`](https://github.com/json-editor/json-editor/blob/cfec910d219082995149babc7d65c3fe926f01bd/src/editors/object.js#L378), which is `this.options.table_row`.
Unit test result:
```
Chrome 81.0.4044 (Linux 0.0.0): Executed 164 of 164 SUCCESS (3.865 secs / 2.715 secs)
TOTAL: 164 SUCCESS
```
Unit test machine:
```
$ uname -a
Linux xxxxxxxx 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu …
```
> Don't display checkbox label when inside object tables

- CHANGELOG.md
- src/defaults.js
- src/editors/table.js
- tests/codeceptjs/editors/array_test.js
- tests/pages/table-move-events.html
Prior to this PR, the "Copy" button would only show up on arrays that are not in the `table` format.  Live examples:
- [`table` format](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgqlUAjiJj2AJqgDaIC1GQBdNggpSENYGg1vKl8IswtCMikpIQUSGTJxK3I8HVMYbUsQA2i2EXgYJyoASSg1ZBQoKREqNjzamPMCsE5ucTYtHKsihSCQqTC6zQ72uKtEBph4AHMFKngROk8QDHSFVzBltjwXdzZ7aBgctjAoVSkQAJBXKiIyEWwMx/2QAF82eDIGNMCnMpAtlt8IWwni83hkPJMZp8DiB/oCrAB1OQ1O7fPwQ36KZRgCi8QzBIyEBbYsg8OAmPqqNEgPBga4gsgQAAsdkczjcvDwgl40Ne71QL2wiGajxgiAgAiF9icLiorl4OEE4rkUrYiCJJMgfAWWsl0skvDIrlceTpcl4IwsYxg4RQEp1IDIHDIAA8Te7rYgyNkqKTrXwOMY/dKA0GdLwsNgBBApVGobLYyGHaFnXU3dH08GLYkhBaramZYHCwkkoqqNInndXdr85W49WS08dDVy6sM0Wa/HIJr6o1pe2hVh4A0w …
> Add copy button to arrays in table format

- config/webpack.dev.js
- config/webpack.nonmin.js
- config/webpack.prod.js
- package.json
- src/core.js
UMD supports both AMD and commonjs2.
so we don't see the need to create two modules.
The build time will be bit shorter.
> Unify the format of the module  to umd.

- src/core.js
- tests/unit/core.spec.js
AbstractEditor, AbstractTheme, AbstractIconlib had been removed in 2.2.0. re-expose them.
| Fixed issues  | #723
At the least, added a tests
> Fix removed static property

- CHANGELOG.md
- src/editors/object.js
Resolves an issue where modal click detection was not working when the editor
is attached inside a shadow DOM by changing the event target to use the path.
| Fixed issues  | #692 
> fix(editors)

- .gitignore
- src/core.js
- src/editors/array.css
- src/editors/array.js
- src/editors/object.css
- src/editors/object.js
- src/editors/table.js
- src/style.css
- src/theme.js
- src/themes/html.css
- tests/unit/core.spec.js
| Fixed issues  | #763
Suggest some theme related fixes.
* selectors in "html theme" is incorrect.
* AbstractTheme.rules is a static property and is not usually read. Change it as the default stylesheet to be read by all themes.
* remove the css rule every time when generating multiple editors on the same page, to prevent to duplicate rules
* css rules of editor, such as ObjectEditor will be integrated into the default rules instead of each theme
* add "undefined" check for custom editor without css rule(#763)
> Some theme related fixes

- README_ADDON.md
- src/theme.js
- tests/codeceptjs/themes_test.js
- tests/pages/themes.html
Theme options have been implemented and documented, but could not be enabled.
Allow to set options when creating the editor.
> Enable theme options

- CHANGELOG.md
- src/editor.js
- tests/codeceptjs/editors/object_test.js
- tests/pages/object-with-dependencies.html
Fixes #703 by not evaluating dependencies independently.
| Fixed issues  | #703
It is possible that users were relying on the previous behavior. This would be unreliable since the visibility is determined by the last dependency evaluated, which would be determined by the order of the watch events. I am not sure this order is documented/guaranteed.
Also, `checkDependency()` was left in place to minimize API changes, but it no longer behaves the same. It no longer calls `notify()` or updates visibility. Also, the state of `dependenciesFulfilled` will  likely be different when calling this …
> Evaluate all dependencies for an editor to determine visibility

- CHANGELOG.md
- src/core.js
- src/defaults.js
- src/editor.js
- src/editors/array.js
- src/editors/base64.js
- src/editors/button.js
- src/editors/checkbox.js
- src/editors/info.js
- src/editors/multiselect.js
- src/editors/object.js
- src/editors/radio.js
- src/editors/select.js
- src/editors/starrating.js
- src/editors/string.js
- src/editors/upload.js
- src/themes/tailwind.js
- src/validator.js
| Fixed issues  | N/A
The PR provides the ability to translate individual text elements, e.g. Titles, InfoTexts, Descriptions while maintaining one definition schema.
It introduces a separate TranslateElement method to keep the JsonEditor translation namespace separate from the user translation one. With the ability to overload the TranslateElement method any way of translation can be applied externally to the json-editor.
One Schema, but json-editor presented in English and German
**Englisch Screen**
**German Screen**
The translations happens outside the json-editor code using a …
> Support to translate user defined elements

- src/validator.js
As user I want to see human-readable error message if a requierd property is not populated. 
Act: error text with the property name as the reference to the failure field
Exp: error test with the property title if exists or otherwise property  name, as the reference to the failure field
This problem is very actual for multi-language projects because user might be not able to match English name of the property and form field label on his own language.
> Replace property name in the error_required message with human readable property title

- README.md
- src/schemaloader.js
- tests/codeceptjs/schemaloader_test.js
- tests/pages/urn.html
- tests/unit/schemaloader.spec.js
| Fixed issues  | #8, #622
Add support for `$ref: 'urn:...'`. If the urn: is not declared locally, calls the `urn_resolver` callback.
> Uniform Resource Name (URN) support for URIs

- CHANGELOG.md
- src/editors/base64.js
If using enum to provide a default value that is read-only, `setValue` should respect the enum rather than overriding it when `keep_values` is enabled.
| Updated README/docs?   | N/A
> Read-only base64 images should respect enum values

- CHANGELOG.md
- package-lock.json
- package.json
- src/editors/string.js
- src/theme.js
| Fixed issues  | #997 
I simply added an aria-label for lone inputs as per [w3.org](https://www.w3.org/WAI/tutorials/forms/labels/#hiding-label-text).  
For inputs with already existing labels, I added a `for` attribute binded with an id added on the input.
This fixes the accessibility issues for string inputs.  
I did not update the tests because there aren't that many changes and I don't see what there is to test but they do pass though. Let me know if I should update them one way or another.
> Add accessibility support for inputs of type "string"

- README.md
- docs/meta_schema.json
- tests/pages/meta_schema.json
The welcome README documentation suggests that both `datetime` and `datetime-local` are supported formats:
But, the HTML standard for the format of an `input` object is `datetime-local`, since `datetime` has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime)
The `json-editor` [samples](https://json-editor.github.io/json-editor/datetime.html) only support `datetime-local`, and in usage`json-editor` appears to only support `datetime-local`.
The PR removes the confusion by removing `datetime` format from the README.
> Remove documentation suggesting datetime is supported

- CHANGELOG.md
- src/editors/table.js
| Fixed issues  |
Added an `aria-hidden="true"` to empty th to pass[ this accessibility rule](https://dequeuniversity.com/rules/axe/4.2/empty-table-header?application=axeAPI).
> Add accessibility support for empty theads

- .gitignore
- CHANGELOG.md
- src/editors/object.js
- tests/codeceptjs/editors/object_test.js
| Is bugfix?    | Yes
| New feature?  | No
| Breaks backward-compatibility?    | No
| Tests pass?   | Hopefully. The unit tests passed but the CodeceptJS tests did not.
| Fixed issues  | #900 
| Updated README/docs?   | Not required
| Added CHANGELOG entry?   | Yes
- Bind `this` fix the modal closing
- Rework the event path to avoid an error outside of Chrome. `event.path` is not standard so `event.path[0]` throws a `ReferenceError`.
- I took a chance that you'd be OK with updating `.gitignore` and the docs. 🤞
> Close the properties modal when we click outside the modal

- docs/cleave.html
- docs/datetime.html
- docs/describedby.html
- docs/index.html
- docs/materialize_css.html
- docs/radio.html
- docs/select2.html
- docs/selectize.html
- docs/starrating.html
- docs/wysiwyg.html
| Tests pass?   | ✔️❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any - https://github.com/json-editor/json-editor/issues/1070
| Updated README/docs?   | N/A
| Added CHANGELOG entry?   | N/A
Scripts using jquery <3.5 expose a vulnerability (https://www.whitesourcesoftware.com/vulnerability-database/CVE-2020-11023, https://vuln.whitesourcesoftware.com/vulnerability/CVE-2019-11358), so move docs scripts to version >3.5.0
> Use latest jquery in scripts to resolve vulnerabilities

- CHANGELOG.md
- README.md
- src/editors/multiselect.js
- tests/codeceptjs/editors/array_test.js
- tests/pages/array-checkboxes-infotext.html
- tests/pages/meta_schema.json
This PR add the feature to specify also info text for enums in an array.
As this is my first contribution to a javascript project, please let me know if I missed something.
I introduce a new option key named `enum`, which holds an array of object.
On each object you can specify:
- `title`: The title of the enum (similar to `enum_titles`)
- `infoText`: The info text showing aside the checkbox
Both keys can are optional.
`enum_titles` was the old way to specify the titles and I left it in for backwards compatibility. …
> add infoText for multiselect enum

- README.md
This is an update to the readme file. It incorrectly says to use the format `html` if you want to use SCEditor. It should be `xhtml`.
> fixed the format documentation to properly use SCEditor

- README.md
- docs/index.html
- docs/starrating.html
- src/themes/bootstrap5.css
- src/themes/bootstrap5.js
- src/themes/index.js
- tests/codeceptjs/themes_test.js
- tests/pages/stepper.html
- tests/pages/themes.html
#1009 
Initial port of bootstrap 5 with goal of low diff from bootstrap4 functionality and appearance.  Followed docs on bootstrap 5.2 website. 
* adds to tests/pages/themes.html
* also changes stepper and starrating docs examples to use bootstrap5 (but these reference the CDN production build of jsoneditor so I used ../dist/jsoneditor.js to test locally)
* Opinion: re-adds css for `.form-group` class with margin-bottom:1rem; (from bootstrap4 -- documented as removed bootstrap 5 so should not conflict).   Did this instead of hard-coding a bottom margin utility, which should continue to allow for easier theme overrides in user code (including backward compatibility for those who may already have done so targeting the bootstrap 4 class)
Initial visual tests seem to past decently 🎉  and …
> Bootstrap 5 - follows migration instructions on bootstrap site.

- src/editor.js
| Fixed issues  | #739 
I reproduced the schema sent by the issuer. The option value was set to _undefined_, so I looked at the code to find where the values are defined. And I found out that a typo when _description_ is set.
> Fix issue #739

- src/editors/object.js
- tests/codeceptjs/editors/issues/issue-gh-1257_test.js
- tests/pages/issues/issue-gh-1257.html
The input type color loses the "html" value when the relative editor is moved to another container element. In this case, a <td> element. This does not happen with other complex inputs like "date", "date-time" or "month" inputs. Setting default value after being moved / appended to <td> fixes the issue and does not triggers any extra change event.
|when being  Q             | A
| Fixed issues  | #[1257](https://github.com/json-editor/json-editor/issues/1257)
> Fix for #1257 (default color doesn't work inside array)

- src/editors/radio.js
- src/editors/select.js
- tests/codeceptjs/editors/issues/issue-gh-1164_test.js
- tests/pages/issues/issue-gh-1164.html
- tests/unit/core.spec.js
Fix for #1164: Null values included in enums for no reason.
Also fixes radio editors not recognising numerical values.
| Fixed issues  | #1164
> Fix for #1164: Null values included in enums for no reason

- tests/codeceptjs/core_test.js
- tests/codeceptjs/editors/issues/issue-gh-1164_test.js
Opportunity to remove not needed `async` functions and calls to old node `assert` functions
> tests: using waitForValue in some tests

- docs/index.html
The [interactive demo](https://json-editor.github.io/json-editor/) fails to load `jquery` prior to loading `selectize`, causing the following console error:
```
selectize.min.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'fn')
at selectize.min.js:3:6679
at selectize.min.js:3:5992
at selectize.min.js:3:6027
```
You can workaround this issue inside the demo by selecting `select2` from the menu *before* multi-selecting `selectize`.
As recommended [here](https://stackoverflow.com/a/20607939), this PR fixes this issue by loading `jquery` prior to loading `selectize` (like as is currently done for select2 within the demo).
| Tests pass?   | N/A
| Fixed …
> Fix issue in interactive demo:  Load jquery before loading selectize

- CHANGELOG.md
- src/editors/array.js
> Fix issue #1453 buttons in array editor are not correctly setup when array editor is initially collapsed

- src/style.css
> Position relative for autocomplete inside arrays table
