docs/index.html
There is a missing comma in the list with stylesheet resources
=> Fix missing comma in resources list

package.json, tests/codeceptjs/wysiwyw-sceditor_test.js, tests/pages/wysiwyg-sceditor.html
Added tests for arrays of html wysiwyg (sceditor) editors.
Also updated the docker-tests command to display tests steps (more verbose)
=> wysiwyg-sceditor tests

src/themes/bootstrap3.js
I Fix the categories format on bootstrap 3
=> Fix categories format on bootstrap 3 (#101)

Gruntfile.js, src/intro.js, src/outro.js
Fixed https://github.com/json-editor/json-editor/issues/25 https://github.com/json-editor/json-editor/issues/127
=> Export as a UMD module

Gruntfile.js, package-lock.json, package.json, src/defaults.js, src/editors/starrating.js, src/styles/starrating.css
- Works with "string" type, so string values are allowed.
- CSS has to be loaded separately. (Using external Stylesheet)
- Stars can be changed to other characters via CSS.
- Placed after label, on a new line like other form elements.
- Displays title/tooltip when hovering.   
- Has option (displayValue) to display the selected rating value.
Live Example: https://codepen.io/pmk/pen/KxbNMo
- Fixed Gruntfile.js problems
- Removed CDN font links from CSS. Now uses Arial font.
=> Pmk65 starrating

README.md, docs/datetime.html, docs/starrating.html, src/editors/starrating.js, src/styles/starrating.css
Updated README.md + fix of datetime example and new starrating example.
Also includes fix of starrating editor.
=> Updated README.md & examples + starrating bugfix

README.md, src/editors/array.js
Fixes issue #185 error and adds an extra option to display array add buttons at the top of the list #30 
To make the buttons appear at the top of the list, set the option "**array_controls_top**" to **true**
If no option is set, it will default to the bottom position.
=> fix of issues #30 and #185

src/editors/object.js
I added an extra check to test if the value is really an object before deleting (Seems like null values fall through the current check.)
=> fix of #131

src/editors/select.js
Fix of #123 
The select editor is missing the "showValidationErrors()" function. So I added the same functionality as in the string editor.
=> Added validation support for select, fixing #123

README.md
related https://github.com/json-editor/json-editor/issues/180#issuecomment-433689965
=> added wiki link

CONTRIBUTING.md
see also https://github.com/json-editor/json-editor/issues/180#issuecomment-433689965
=> added "Contributing Use-cases"

src/editor.js
Changed the 50 character limit to 500
=> Fix of #140 - pattern of greater than 35 chars doesn't display properly

src/editor.js, src/editors/array.js, src/editors/checkbox.js, src/editors/rating.js, src/editors/select.js, src/editors/selectize.js, src/editors/signature.js, src/editors/starrating.js, src/editors/string.js, src/editors/table.js, src/iconlib.js, src/iconlibs/materialicons.js, src/theme.js, src/themes/bootstrap2.js, src/themes/bootstrap3.js, src/themes/bootstrap4.js, src/themes/foundation.js, src/themes/jqueryui.js, src/themes/materialize.js
Refactored use of Element.className into Element.classList (There are a few className references left which I wasn't sure how to modify)
=> Refactoring className into classList

src/editors/datetime.js
Fixed setValue in JSONEditor.defaults.editors.datetime
=> Fixed setValue in datetime

README.md
added already implemented enable_array_copy option to Readme.
=> Added enable_array_copy to README.md

README.md
- Changed example links from old jdorn repo to new one.
- Added links to additional examples in docs/ folder.
- Added link to Signature Pad source.
=> Updated links in README.MD

src/intro.js
Replaces the deprecation notice from the intro. The new text is merely a proposal to get started; feel free to alter.
Fixes #234
=> Remove deprecation notice from intro

Gruntfile.js
=> Actually run the version string replacement

README.md, src/editors/string.js, tests/pages/string-custom-attributes.html
Since there was no feedback from @germanbisurgi on #10, I decided to change the format.
Also added missing documentation to README.MD
=> Inputattributes change

src/editors/object.js, src/theme.js, src/themes/bootstrap2.js, src/themes/bootstrap3.js, src/themes/bootstrap4.js, src/themes/foundation.js, src/themes/jqueryui.js, src/themes/materialize.js
- Solve issues about rendering HTML
- Solve simple Materialize problems. Materialize doesn't include tabs-top and categories support. I will add this on a next PR.
=> Solve Issue #214

README.md, docs/demo.html, docs/index.html, src/iconlibs/fontawesome5.js
Implement https://github.com/json-editor/json-editor/issues/250
Screenshot of the demo page
=> Support fontawesome 5

docs/cleave.html
Forgot to change the local path in the example. 😜
=> fixed javascript path

README.md, src/editors/select.js
Added typecasting of Rendered value in onWatchedFieldChange function.
=> Fix of #270

src/themes/bootstrap4.js
=> Fix bootstrap4 theme so errors are colored

src/editors/string.js
- Fix of #290 
- Added Cleavejs global instance + destroy functionality.
=> Destroyfix

src/editors/object.js
=> Added CopyToClipboard in JSON Modal

src/defaults.js, src/themes/bootstrap4.js
Added dummy default upload handler, so instead of terminating it will output a console message if no custom upload handler is defined.
=> Added default upload handler

src/defaults.js, src/editors/object.js
The Object Properties Button had a hardcoded Text and could not be translated.
=> Added missing Object Properties Translation

src/editors/datetime.js, src/validator.js
Fix of #347, #324, #312 and #323
=> Fix of #347, #324, #312 and #323 

README.md
- see also https://github.com/json-editor/json-editor/pull/332
=> :memo: about underscore version

Gruntfile.js, README.md, docs/describedby.html, src/defaults.js, src/editors/describedby.js, src/validator.js
=> Hyper-Link DescribedBy Editor

README.md
Another "hidden feature" that haven't been documented. 😁 
Originates from https://github.com/jdorn/json-editor/pull/719
=> MMissing infoText documentation

README.md, src/editor.js, src/editors/array.js, src/editors/object.js, src/themes/bootstrap3.js, src/themes/bootstrap4.js, src/themes/foundation.js, tests/codeceptjs/editors/grid_test.js, tests/codeceptjs/editors/object_test.js, tests/pages/grid-strict.html, tests/pages/grid.html, tests/pages/object-required-properties.html
Allows to set grid_size, grid_offset and grid_break
=> format grid-strict

README.md, src/editor.js
=> Fix of #361

README.md
Added missing link to Radio Button editor example.
=> link to radio button example

README.md, src/editor.js
Fix of #365 
Link to JSON-Editor Interactive Playground added to docs (I don't think it's a good idea to include the code in the JSON-Editor package, as it's quite big)
=> Horizontaldepfix

src/editors/array/selectize.js, tests/codeceptjs/editors/array_test.js, tests/pages/array-selectize.html
While using selectize, overrided "selectize_options" were not applied to selectize instance created by arraySelectize.
Fixed error.
=> fix apply global selectize options to arraySelectize

README.md
Added documentation on 2 "hidden" features.
See https://github.com/json-editor/json-editor/issues/367
=> Added missing options ajaxBase and ajaxCredentials

tests/codeceptjs/codecept.json, tests/codeceptjs/editors/string_test.js, tests/docker-compose.yml
Naming convetion for the selenium docker images making make troubles
https://stackoverflow.com/questions/56452798/how-to-turn-off-w3c-in-chromedriver-to-address-the-error-unknown-command-cannot
https://github.com/SeleniumHQ/docker-selenium/issues/917
https://hub.docker.com/r/selenium/node-chrome/tags
=> fix for multiple browser testing

src/core.js, src/editors/array.js
Copying array items didn't send events, now they do.
Array events now include added/removed/moved editor as first argument.
=> Improvements to array change events.

src/themes/tailwind.js
Tailwind Theme by @mirannda #391
=> Tailwind Theme by @mirannda #391

CHANGELOG.md, src/defaults.js, src/validator.js
Fixes problem with upload editor (Was actually the new "describedBy" editor that caused the problems.)
=> Fix of #408

src/editors/multiple.js, src/validator.js
| Breaks BC?    | ❌
| Fixed issues  | #128 #444
=> choose the best fit schema in the oneOf

.github/PULL_REQUEST_TEMPLATE.md
| New feature?  |❌
| Breaks BC?    |❌
| Tests pass?   | n/a
=> added more questions for PR

CHANGELOG.md, src/themes/tailwind.js
| Breaks BC?    | ❌
| Fixed issues  | #466
=> Tailwind 2.x Theme by @mirannda

tests/README.md
| New feature?  |❌
| Added CHANGELOG entry?   | ❌ (just docs)
=> :memo: grunt watch (npm start)

src/themes/spectre.js
=> Added Spectre Theme adjustment styling for Choices.js

.travis.yml, package.json
=>     Simplify Codeceptjs Scripts

tests/codeceptjs/editors/button_test.js, tests/pages/button-callbacks.html
My 1st attempt of writing an ConceptJS test.
=> Tests for Button Editor

src/editors/button.js, src/editors/info.js, src/editors/string.js, tests/README.md, tests/codeceptjs/editors/button_test.js, tests/codeceptjs/editors/string_test.js, tests/pages/button-callbacks.html, tests/pages/string-cleave.html
| Tests pass?   | ✔️ and ❌ 
| Fixed issues  | #494
| Added CHANGELOG entry?   |❌
Although this fixes the original issue, for some reason I can't get the second codecept test to pass. When I run the steps from the test manually, everything works as expected. 
Can anyone advise I can easily debug codecept tests (ideally outside docker) or give any other advice on why this test may be failing?
=> Fix defaults

package-lock.json, package.json, src/editors/button.js, src/editors/info.js, src/editors/string.js, tests/README.md, tests/codeceptjs/editors/button_test.js, tests/codeceptjs/editors/string_test.js, tests/pages/button-callbacks.html, tests/pages/string-cleave.html
=> Sirockin fix defaults

package-lock.json, package.json, tests/codeceptjs/editors/button_test.js, tests/codeceptjs/editors/jodit_test.js, tests/codeceptjs/editors/string_test.js, tests/pages/button-callbacks.html, tests/pages/string-jodit-editor.html
=> Updated Button editor test + Test for Jodit editor

tests/codeceptjs/editors/object_test.js, tests/pages/object-no-additional-properties.html
| Demonstrates issues  | #509 
| Updated README/docs?   |❌
=> Added failing test to demonstrate #509

src/defaults.js
=> Fix of #514 - Multiselect didn't work with array tables

src/defaults.js, src/editors/array.js
Closes #525
| Fixed issues  | #525
=> Translate default array item title

src/editor.js
=> Hides children instead of wrapper when dependencies is used in table

src/editors/ip.js
=> Fix cleave integration in IP editor

CHANGELOG.md, README.md, src/editors/table.js, tests/codeceptjs/editors/array_test.js, tests/pages/array-move-events.html, tests/pages/table-move-events.html
| Breaks backward-compatibility? | ❌
| Tests pass? | ✔️
| Updated README/docs? | ✔️
| Added CHANGELOG entry? | ✔️
=> Array events also for table editor + tests + documentation (without merge conflicts)

tests/pages/array-anyof.html
| Tests pass?   | ❌
| Fixed issues  | test case for #459 
=> new test page `array-anyof.html` without test case.

src/editors/object.js, tests/codeceptjs/editors/object_test.js
=> Child editors were incorrectly enabled when opted out.

CHANGELOG.md, README.md, src/editors/object.js, src/editors/table.js, tests/codeceptjs/editors/array_test.js, tests/codeceptjs/editors/object_test.js, tests/pages/table-move-events.html
"last" porting of changes from master to develop/2.x due to #546
=> Feature/porting master to 2.x 190917

config/codeceptjs_helpers.js, tests/codeceptjs/editors/jodit_test.js, tests/codeceptjs/editors/string_test.js, tests/codeceptjs/steps_file.js
| Breaks backward-compatibility?  ❌
| Fixed issues  | #563, #559
| Updated README/docs? | ❌
| Added CHANGELOG entry? | ❌
=> Fix for  #563, #566 & #559 (pressKey not working anymore)

src/editors/sceditor.js
=> SCEditor without jQuery.

package-lock.json, package.json
| Is bugfix?    | ✔️/❌
| Breaks backward-compatibility?    | ✔️/❌
=> Release 2.0.0-alpha.0

README.md, docs/choices.html, docs/index.html, docs/select2.html, docs/selectize.html
| Fixed issues  | #556
**README.md update**
- Added links to new resources. (Autocomplete, Jodit, IMask)
- Removed references to outdated plugin configuration.
- Removed references to jQuery wrapper.
=> Fix of examples to match the 2.x version

src/editors/sceditor.js
=> SCEditor: Use input_type as is.

docs/index.html
- see also https://github.com/json-editor/json-editor/issues/610
| Tests pass?   | n/a
| Fixed issues  | related #610 
=> added show_opt_in to demo

.env-dist, .gitignore, Makefile, tests/README.md, tests/docker-compose.yml
| Tests pass?   | n/a
| Fixed issues  | none
=> added basic Makefile

src/editors/upload.js
- Added afterInputReady functionality.
=> Refactoring upload.js

.travis.yml
=> travis-ci stages (almost)

CHANGELOG.md, config/codeceptjs_helpers.js, package-lock.json, package.json, src/themes/bootstrap4.js, tests/codeceptjs/editors/array_test.js, tests/codeceptjs/editors/object_test.js
Fix of #629 - BS4 theme bug where basic tab was placed outside tabs container.
| Fixed issues  | #629 
=> Fix of #629 

docs/basic_person.json, docs/index.html, tests/fixtures/basic_person.json
| Is bugfix?     ✔️
| New feature?  ❌
| Breaks backward-compatibility?   ✔️
| Tests pass?   ✔️
| Updated README/docs?  ❌
| Added CHANGELOG entry?  ❌
=> add "other" to test enums

package-lock.json
| Tests pass?   | ?
| Fixed issues  | Notice from GitHub Security Bot
| Updated README/docs?   | n/a
| Added CHANGELOG entry?   | n/a
=> npm fix audit

package-lock.json, package.json, tests/codeceptjs/themes_test.js
| Fixed issues  | https://github.com/json-editor/json-editor/commit/1e44cde32d38a1259b55aa2cf89c349a0a0438ca
=> Release 2.0.0-alpha.1

UPGRADING.md
HTML no longer passed in descriptions @see #83155ea
| Is bugfix?    | ✔️/❌
| Breaks backward-compatibility?    | ✔️/❌
=> Mention DomPurify in Upgrading

docs/index.html, src/core.js
| Tests pass?   | ✔️?
| Fixed issues  | fixed interactive page disaster. Exposed abstract icon lib
| Added CHANGELOG entry?   |❌
=> Interactive page disaster fix and #658

package.json, src/core.js, src/editors/array/choices.js, src/editors/array/selectize.js, src/editors/choices.js, src/editors/hidden.js, src/editors/object.js, src/editors/select.js, src/editors/selectize.js, src/editors/simplemde.js, src/editors/string.js, src/editors/table.js, src/validator.js
| Fixed issues  | fixed docker-tests npm targe, eslint errors
=> fixed docker-tests npm target and eslint errors

README.md, UPGRADING.md, config/webpack.common.js, package-lock.json, package.json
In preparation for using const, let, arrow functions, etc. in the future, we will explain how to use it with legacy browsers in the README and add Babel.
=> Support legacy browsers in README and Babel

src/utilities.js
| Is bugfix?    | 
| Fixed issues  | #648
=> proof null before everything else to avoid undefined variables  #648

.npmignore, package-lock.json, package.json
| Is bugfix?    | ✔️/❌
| Breaks backward-compatibility?    | ✔️/❌
=> Version 2.0.0

src/editors/string.js, tests/codeceptjs/editors/integer_test.js, tests/codeceptjs/editors/number_test.js, tests/pages/integer.html, tests/pages/number.html
=> Update output when calling setValue on range input

src/editors/multiple.js
=> fix lint error

docs/cleave.html, docs/colorpicker.html, docs/css_integration.html, docs/datetime.html, docs/describedby.html, docs/enumsource.html, docs/radio.html, docs/recursive.html, docs/select2.html, docs/selectize.html, docs/starrating.html, docs/wysiwyg.html
=> Update external links and options of examples

README.md
=> Document options delete all and delete last row

src/editors/upload.js
| Fixed issues  | [#712](https://github.com/json-editor/json-editor/issues/712)
=> Fix outdated event object, upload editors

src/defaults.js, tests/unit/defaults.spec.js
=> Fixed a bug that language customization did not reflect.

src/editors/colorpicker.js, src/editors/object.js
=> fix for #662 and #718

CHANGELOG.md, package-lock.json
=> prepare release 2.2.0

src/schemaloader.js, tests/unit/schemaloader.spec.js
=> Fix parameter order and Add test case

CHANGELOG.md
| New feature?  |❌
| Tests pass?   | n/a
| Updated README/docs?   | n/a
=> changelog for 2.2.1

CHANGELOG.md, src/editors/object.js, tests/unit/editors/object.spec.js
Sorry. My fault.
Add null check (removed in #691 )
Add unit test
| Fixed issues  | #725
=> Fix #725 remove_empty_properties

src/editors/object.js, src/theme.js, src/themes/bootstrap4.js, src/themes/spectre.js
=> fix #736, #733

.travis.yml, CHANGELOG.md, Makefile, tests/Dockerfile, tests/README.md, tests/codeceptjs/steps.d.ts, tests/docker-compose.yml, tests/pages/_demo.html, tests/pages/issues/_template.html
| Breaks backward-compatibility?    | slightly for testing
=> [WIP] Feature/remove codeception container

README.md
| Fixed issues  | #742 
| Added CHANGELOG entry?   | n/a
=> fixed #742, corrected CDN links

config/codeceptjs_helpers.js, src/themes/bootstrap4.js, tests/codeceptjs/editors/object_test.js, tests/pages/object-no-duplicated-id.html
=> better fix for 736

src/defaults.js, src/editors/array.js
=> Add node deletion message to translation dictionnary

CHANGELOG.md, docs/index.html, package-lock.json, src/iconlibs/index.js, src/themes/bootstrap3.js, src/themes/index.js, tests/codeceptjs/themes_test.js
| Breaks backward-compatibility?    | no
=> enabled Bootstrap3 theme and icons

src/themes/spectre.js
| Fixed issues  | [#670](https://github.com/json-editor/json-editor/issues/670)
=> Fix headerTemplate for Spectre theme

src/editors/upload.js
=> #743 Upload bug

src/utilities.js
| Fixed issues  | #786 
This PR is the same as @partikule https://github.com/json-editor/json-editor/pull/788 except with linting error fixed.
=> Fixed the console error when using describedBy

src/schemaloader.js
=> Fix loading data and blob schemas URIs via Ajax

src/editors/array.js, src/editors/table.js, tests/unit/editor.spec.js
* Add workaround for non-array values being set to the table (#777)
* Split functions that are too long into several parts (#667)
| Fixed issues  | #777, #667 
=> Refactor array.js and table.js

src/editors/datetime.js, tests/codeceptjs/editors/datetime_test.js, tests/pages/datetime.html
=> max and min for time, date and datetime local + tests

CHANGELOG.md
| Is bugfix?    | ✔️/❌
| Breaks backward-compatibility?    | ✔️/❌
=> Update CHANGELOG.md for 2.4.0

README.md
=> added Override Editors Methods section in readme

config/webpack.common.js, config/webpack.prod.js, docs/index.html, docs/polyfills/assign.js, package-lock.json, package.json
| Fixed issues  | not working in IE and browsers that have still not covered new es6 features 
=> Fix Babel not transpilling Bug. Fix checkbox editor not displaying error messages Bug

src/editors/checkbox.js, src/resolvers.js
| Fixed issues  | #837
| Added CHANGELOG entry?   |❌
=> Fix for #837 and chekboxes not displaying error messages

src/editor.js, tests/codeceptjs/core_test.js, tests/pages/form-name.html
=> should change the form if form_name_root option is set

release-notes.md
=> added npm release notes

src/editor.js, src/validator.js, tests/codeceptjs/core_test.js, tests/pages/form-name.html
=> Fixes issues related to hard coded form_root_names (displaying errors)

src/editors/stepper.js, src/theme.js, src/themes/bootstrap4.js
=> fix stepper safari bug

CHANGELOG.md, package-lock.json, package.json, src/defaults.js, src/editors/object.js, src/validator.js, tests/codeceptjs/editors/validation_test.js, tests/fixtures/validation.json
=> Property names

src/editors/button.js, src/editors/checkbox.js, src/editors/multiselect.js, src/editors/radio.js, src/editors/select.js, src/editors/signature.js, src/editors/starrating.js, src/editors/string.js, src/editors/uuid.js, tests/codeceptjs/editors/array_test.js, tests/codeceptjs/editors/button_test.js, tests/codeceptjs/editors/radio_test.js, tests/pages/read-only.html
=> add more read-only tests for #831

src/schemaloader.js, tests/unit/schemaloader.spec.js
=> fixes #379 and #923 - strip #fragment from URI so json pointers resolve correctly

src/editors/array.js, tests/unit/editors/array.spec.js
| Fixed issues  | #159, #285, #820
=> fixes #159, #285, #820 - setting array with 0, false, or ""

.eslintrc, src/defaults.js, src/editors/autocomplete.js, src/editors/upload.js, src/schemaloader.js, src/themes/bootstrap4.js, src/themes/spectre.js, src/validator.js
=> remove unnecessary console.log() calls; enable eslint rule for no-console

src/editors/object.js
=> fix: #812 (Deletion of array item corrupts form data )

.github/workflows/build.yml
| Updated README/docs?   | n/a
| Added CHANGELOG entry?   | n/a
=> updated build

src/schemaloader.js, tests/unit/schemaloader.spec.js
=> Fix relative $ref issue discussed in #923

.github/workflows/build.yml
Fixes typo in the build log message.
=> Rename acitons to actions

src/defaults.js, src/validator.js, tests/codeceptjs/editors/validation_test.js, tests/fixtures/validation.json
=> fixes #636 add const

src/editor.js, tests/codeceptjs/editors/object_test.js, tests/pages/object-with-dependencies-array.html
=> Multiple dependency values

src/editors/table.js, tests/unit/editors/array.spec.js, tests/unit/editors/table.spec.js
| Fixed issues  | #976 (see also #820)
#820 only fixed the issue in array.js; #976 shows the problem also exists in table.js
=> Falsy values

README_ADDON.md
=> added autocomplete example

src/schemaloader.js
| Fixed issues  |  NA
| Updated README/docs?   | NA
=> If a global variable 'value' is defined it breaks the type dropdown.

src/editors/radio.js, tests/codeceptjs/editors/object_test.js, tests/pages/object-required-properties.html
=> updated radio editor and test (required was forced on radio editors)

src/themes/bootstrap4.js
Fixes #1023
| Tests pass?   | ✔️❌
| Fixed issues  | #1023 
=> Add level-n class to h3 headers in Bootstrap theme

tests/codeceptjs/editors/button_test.js
| Is bugfix?    | ✔️ hardening
=> added retry to test

src/editor.js, tests/codeceptjs/editors/object_test.js, tests/pages/object-with-dependencies-array.html
=> Fix for dependencies when dependency is an array

package-lock.json, package.json, tests/pages/string-simplemde-editor.html
=> Add SimpleMDE test page.

.github/workflows/build.yml, CHANGELOG.md, README.md, src/core.js, src/schemaloader.js, src/style.css, tests/codeceptjs/codecept.json, tests/codeceptjs/editors/advanced_test.js, tests/fixtures/definitions.json, tests/fixtures/properties.json, tests/pages/array-move-events.html, tests/pages/core.html, tests/pages/grid-strict.html, tests/pages/grid.html, tests/pages/issues/issue-gh-812.html, tests/pages/object-required-properties.html, tests/pages/references.html, tests/pages/table-move-events.html, tests/pages/urn.html, tests/unit/core.spec.js, tests/unit/editor.spec.js, tests/unit/editors/array.spec.js, tests/unit/editors/object.spec.js, tests/unit/editors/table.spec.js, tests/unit/schemaloader.spec.js, tests/unit/validator.spec.js
| Fixed issues  | #988 
PR from https://github.com/json-editor/json-editor/pull/994 with hardened test
=> Cybtachyon cybtachyon/988  json pointers

README.md, docs/form-submission.html
Updated Readme and added form submission case study example
=> Added form submission case study and linked it in the readme intro

src/core.js, tests/codeceptjs/core_test.js, tests/pages/ready.html
=> .je-ready class when ready

src/themes/bootstrap3.js, src/themes/spectre.js
=> Add info text for checkbox on "Spectre" and "Bootstrap 3" Themes

README.md
Show the warning in a separate quote to make it more visible
=> Show warning that callbacks must be defined

src/editors/object.js
=> Keep reference of eventListener to later remove it.

src/defaults.js, src/editors/upload.js
=> Added upload translations

src/editors/object.css
| Tests pass?   | ✔️❌
| Fixed issues  | #1221
=> Remove !important flag in editor textarea style

src/editors/upload.js
=> no message

docs/meta_schema.json
=> removed excess comma

docs/datetime.html
=> Fix issue #1209

CHANGELOG.md, src/resolvers.js
=> Add support for shell script highlighting

src/themes/bootstrap3.js
| Tests pass?   | ✔️❌
| Fixed issues  | 1298
| Updated README/docs?   | ✔️❌
| Added CHANGELOG entry?   | ✔️❌
=>  fix import warning boostrap 3 analogue to bootstrap 4 import

README.md, docs/css_integration.html
=> Corrected theme readme and example page

docs/custom-editor.html
issue #1327
Example of how to create custom editors
=> Added custom editor example

src/validator.js, tests/codeceptjs/constrains/if-then-else_test.js, tests/pages/if-else.html, tests/pages/if-then-else.html, tests/pages/if-then.html
=> Added if-then-else validator plus tests with different scenarios

src/editors/multiple.js, src/resolvers.js, src/utilities.js, tests/codeceptjs/constrains/if-then-else_test.js, tests/pages/if-then-else-allOf.html
=> if then else reflected in ui

tests/codeceptjs/issues/issue-gh-1338_test.js, tests/pages/issues/issue-gh-1338.html
test for issue #1338
test case for if then else
=> Test for issue 1338

package-lock.json, package.json
=> Sync master after release

README.md
=>  documentation for if-then-else in readme

CHANGELOG.md, README.md, README_ADDON.md, docs/meta_schema.json, src/resolvers.js, tests/pages/meta-schema.html, tests/pages/meta_schema.json
=> Add languages

CHANGELOG.md, README.md, src/defaults.js, src/editors/object.js, tests/codeceptjs/editors/object_test.js, tests/pages/object-case-sensitive-property-search-false.html, tests/pages/object-case-sensitive-property-search-true.html
=> Feature/case sensitive property search + tests

README.md
=> Updated broken link in README.md

src/editors/simplemde.js, tests/codeceptjs/issues/issue-gh-1431_test.js, tests/pages/issues/issue-gh-1431.html
=> Fix for issue #1431 + test

CHANGELOG.md, src/editors/array.js, tests/codeceptjs/issues/issue-gh-1453_test.js, tests/codeceptjs/issues/issue-gh-1461_test.js, tests/pages/issues/issue-gh-1453.html, tests/pages/issues/issue-gh-1461.html
| Fixed issues  | #1461, added test for #1453
=> Fix issue #1461

src/themes/bootstrap3.js, tests/codeceptjs/issues/issue-gh-1491_test.js, tests/pages/issues/issue-gh-1491.html
=> Fixed issue 1491, wrong error message shown

src/editors/radio.js, tests/codeceptjs/issues/issue-gh-1171_test.js, tests/pages/issues/issue-gh-1171.html
=> Fixed radios multichecking bug when not using names

src/editors/string.js, tests/codeceptjs/issues/issue-gh-1485_test.js, tests/pages/issues/issue-gh-1485.html
=> Fix infinite loop due to templates

src/editors/multiple.js
=> visually hide label but still screen reader readable

src/editors/info.js
=> Fixed editor format info disable/enable bug causing error

src/editor.js
| Fixed issues  | ##1514, #1518
=> Fixed error when setting more than one class in options

README.md, docs/meta-schema.html
=> Added meta schema example in docs and readme

src/editors/starrating.js, tests/codeceptjs/editors/rating_test.js, tests/codeceptjs/editors/starrating_test.js, tests/pages/starrating.html, tests/unit/editor.spec.js
| Fixed issues  | #1486, #1527
=> WIP: Fix rating "undefined" value when type of integer

src/schemaloader.js, tests/codeceptjs/issues/issue-gh-1541_test.js, tests/pages/issues/issue-gh-1541.html, tests/pages/issues/issue-gh-1541.json
we sould ensure that shema is not null
| Fixed issues  | [1541](https://github.com/json-editor/json-editor/issues/1541)
=> ISSUE-1541 default null in reference

README.md, src/core.js, src/editor.js, src/editors/array.js, src/editors/describedby.js, src/editors/multiple.js, src/editors/object.js, src/editors/table.js
=> Added new events 'add' and 'switch' to track changes

src/editor.js, src/editors/base64.js
It could be handy in some cases
| Fixed issues  | --
=> Base64 allow for custom input attributes

README.md, src/defaults.js, src/editors/object.js, tests/codeceptjs/editors/object_test.js, tests/pages/remove-false-properties.html
=> Remove false properties option for object editors

src/editors/select2.js, tests/codeceptjs/issues/issue-gh-1525_test.js, tests/pages/issues/issue-gh-1525.html
=> Fixed select2 adding new items bug

src/editors/object.js, tests/codeceptjs/issues/issue-gh-1562_test.js, tests/pages/issues/issue-gh-1562.html
=> Fixed 1562 + test

src/editors/array.js, src/editors/object.js, tests/codeceptjs/issues/issue-gh-1586_test.js, tests/pages/issues/issue-gh-1586.html
Recursively deactivate non required properties, when adding a new row in an array.
| Fixed issues  | #1586 
=> Fixed issue #1586

.github/workflows/build.yml
| Fixed issues  | broken build, eg. https://github.com/json-editor/json-editor/actions/runs/10493891435/job/29092307134
=> fixed docker compose command

CHANGELOG.md, README.md, src/editors/array.js, src/editors/table.js
| Tests pass?   | N.A.
| Fixed issues  | #448  
=> support drag and drop for array item

src/core.js, src/editors/array.js, src/editors/checkbox.js, src/editors/select.js
=> Allow displaying third party error messages

docs/form-submission.html
| Is backward-compatible?    | ❌
The submit button is redirecting to the wrong page, remove the action attribute to redirect to the actual page
=> Fix form submission example demo
